### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by Alirun**
Typo fix

### CODE REVIEW

**Review by auryn-macmillan — APPROVED** [review]
Thanks for this :smile:

**Review by auryn-macmillan — APPROVED** [review]

**Review by auryn-macmillan — APPROVED** [review]

**Review by auryn-macmillan — APPROVED** [review]

**Review by auryn-macmillan — APPROVED** [review]

**Comment by auryn-macmillan** [comment]
recheckcla

**Comment by auryn-macmillan** [comment]
@Alirun, could you please accept the CLA so we can merge this change?

**Comment by Alirun** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Alirun** [comment]
recheckcla

**Pull request merged**
