### PR TITLE
Update README with SafeSnap plugin name

### PR DESCRIPTION
**Pull request by bonustrack**
Just small change to tell the plugin is now called SafeSnap on Snapshot and how the format of the parameters should look like.

### CODE REVIEW

**Review by auryn-macmillan — APPROVED** [review]
Looks good to me! Thanks.

**Comment by rmeissner** [comment]
recheckcla

**Comment by bonustrack** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by auryn-macmillan** [comment]
recheckcla

**Comment by auryn-macmillan** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by auryn-macmillan** [comment]
recheckcla

**Review by auryn-macmillan — APPROVED** [review]

**Comment by auryn-macmillan** [comment]
recheckcla

**Comment by auryn-macmillan** [comment]
@rmeissner, what what else do we need to do to get the CLA bot to approve this

**Pull request merged**
