### PR TITLE
Update Zodiac dependency, bump version

### PR DESCRIPTION
**Pull request by auryn-macmillan**

### CODE REVIEW

**Review by cbrzn — APPROVED** [review]

**Comment by auryn-macmillan** [comment]
@carlosfebres could you please post this in a comment here
>  I have read the CLA Document and I hereby sign the CLA

**Comment by carlosfebres** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by auryn-macmillan** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by auryn-macmillan** [comment]
recheckcla

**Comment by auryn-macmillan** [comment]
@rmeissner not sure what's blocking this. Can you help?

**Pull request merged**
